name: untitled
version: '1.0-SNAPSHOT'
main: blackjack.blackjack.Blackjack
api-version: '1.20'
commands:
  blackjackstart:
    description: Summons blackjack game for command sender. 
      Visit "spigotmc.org/resources/blackjack" for FAQ and information on how to play.
    usage: /blackjackstart
    aliases: ["blackjack", "start"]


